# Generated by Django 6.0.5 on 2026-05-17 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True)),
                ('draw_date', models.DateTimeField(blank=True, null=True)),
                ('is_drawn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField()),
                ('is_auto', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(1, '1등'), (2, '2등'), (3, '3등'), (4, '4등'), (5, '5등')])),
                ('prize_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.round')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lottery.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='WinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_numbers', models.JSONField()),
                ('bonus_number', models.IntegerField()),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lottery.round')),
            ],
        ),
    ]
